services:
  - type: web
    name: audiobook-translator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python src/app.py
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
    healthCheckPath: /health
